# New ports collection makefile for:	R-cran-pROC
# Date created:		2012-01-06
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD$
#

PORTNAME=	pROC
PORTVERSION=	1.5
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Display and analyze ROC curves

LICENSE=	GPLv3

RUN_DEPENDS=	R-cran-plyr>0:${PORTSDIR}/devel/R-cran-plyr

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
