# $FreeBSD: $

PORTNAME=	pango
PORTVERSION=	1.1.5
CATEGORIES=	x11-toolkits ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=        Ruby binding for Pango

RUN_DEPENDS=	rubygem-cairo>=1.10.0:${PORTSDIR}/graphics/rubygem-cairo \
		rubygem-glib2>=1.1.5:${PORTSDIR}/devel/rubygem-glib2

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
