# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/textproc/p5-Text-HikiDoc/Makefile 318504 2013-05-19 09:15:02Z tota $

PORTNAME=	Text-HikiDoc
PORTVERSION=	1.021
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Pure Perl implementation of 'HikiDoc'

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_MODBUILD=	yes

MAN3=	Text::HikiDoc::Plugin.3 Text::HikiDoc.3

.include <bsd.port.mk>
