# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/astro/R-cran-maptools/Makefile 347809 2014-03-10 20:55:20Z gerald $

PORTNAME=	maptools
DISTVERSION=	0.8-29
PORTREVISION=	1
CATEGORIES=	astro
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Tools for reading and handling spatial objects

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

RUN_DEPENDS=	R-cran-sp>=1.0.11:${PORTSDIR}/math/R-cran-sp

USES=	cran:auto-plist

.include <bsd.port.mk>
