# New ports collection makefile for:	R-cran-e1071
# Date created:		2011-09-03
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: head/science/R-cran-e1071/Makefile 300897 2012-07-14 14:29:18Z beat $
#

PORTNAME=	e1071
DISTVERSION=	1.6-1
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Misc Functions of the Department of Statistics (e1071), TU Wien

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
