# New ports collection makefile for:	R-cran-e1071
# Date created:		2011-09-03
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD$
#

PORTNAME=	e1071
DISTVERSION=	1.5-27
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Misc Functions of the Department of Statistics (e1071), TU Wien

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
