# New ports collection makefile for:	R-cran-iterators
# Date created:		2011-08-16
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/devel/R-cran-iterators/Makefile,v 1.4 2011/11/27 07:02:07 bf Exp $
#

PORTNAME=	iterators
PORTVERSION=	1.0.5
PORTREVISION=	2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Iterator construct for R

LICENSE=	ASL

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
