# New ports collection makefile for:	R-cran-iterators
# Date created:		2011-08-16
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/devel/R-cran-iterators/Makefile,v 1.7 2012/03/03 16:59:26 bf Exp $
#

PORTNAME=	iterators
PORTVERSION=	1.0.5
PORTREVISION=	4
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Iterator construct for R

LICENSE=	AL2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
