# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/converters/R-cran-rjson/Makefile 347809 2014-03-10 20:55:20Z gerald $

PORTNAME=	rjson
PORTVERSION=	0.2.14
CATEGORIES=	converters
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	JSON for R

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
