# New ports collection makefile for:	R-cran-rjson
# Date created:		2012-02-21
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/converters/R-cran-rjson/Makefile,v 1.2 2012/03/03 16:59:25 bf Exp $
#

PORTNAME=	rjson
PORTVERSION=	0.2.7
CATEGORIES=	converters
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	JSON for R

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
