# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/converters/R-cran-rjson/Makefile 301500 2012-07-24 21:38:27Z tota $

PORTNAME=	rjson
PORTVERSION=	0.2.10
CATEGORIES=	converters
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	JSON for R

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
