# New ports collection makefile for:	rubygem-net-irc
# Date created:		2010-09-29
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/irc/rubygem-net-irc/Makefile,v 1.2 2010/10/01 14:18:18 tota Exp $
#

PORTNAME=	net-irc
PORTVERSION=	0.0.9
CATEGORIES=	irc rubygems
MASTER_SITES=	RG

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Ruby library for implementing IRC server and client

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
