# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/databases/R-cran-DBI/Makefile 313562 2013-03-07 04:21:34Z bf $

PORTNAME=	DBI
DISTVERSION=	0.2-6
CATEGORIES=	databases
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	R Database Interface

LICENSE=	LGPL20 LGPL21 LGPL3
LICENSE_COMB=	dual

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
