# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/security/R-cran-digest/Makefile 337846 2013-12-28 10:28:40Z dbn $

PORTNAME=	digest
PORTVERSION=	0.6.3
PORTREVISION=	4
CATEGORIES=	security
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Create cryptographic hash digests of R objects

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
