# New ports collection makefile for:	R-cran-digest
# Date created:		2011-09-04
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/security/R-cran-digest/Makefile,v 1.7 2012/03/03 16:59:35 bf Exp $
#

PORTNAME=	digest
PORTVERSION=	0.5.2
CATEGORIES=	security
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Create cryptographic hash digests of R objects

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
