# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-zoo/Makefile 337846 2013-12-28 10:28:40Z dbn $

PORTNAME=	zoo
DISTVERSION=	1.7-11
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	S3 Infrastructure for Regular and Irregular Time Series

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
