# New ports collection makefile for:	R-cran-pixmap
# Date created:		2011-12-21
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/graphics/R-cran-pixmap/Makefile,v 1.1 2012/02/26 22:22:25 tota Exp $
#

PORTNAME=	pixmap
DISTVERSION=	0.4-11
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Bitmap Images ("Pixel Maps")

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
