# Ports collection makefile for:	rubygem-eventmachine
# Date created:				01 April 2007
# Whom:					Alexander Logvinov <ports@logvinov.com>
#
# $FreeBSD: ports/devel/rubygem-eventmachine/Makefile,v 1.15 2010/12/08 23:08:02 avl Exp $

PORTNAME=	eventmachine
PORTVERSION=	1.0.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A fast, simple event-processing library for Ruby programs

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
