# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-deldir/Makefile 304003 2012-09-09 21:47:00Z tota $

PORTNAME=	deldir
DISTVERSION=	0.0-21
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Delaunay Triangulation and Dirichlet (Voronoi) Tessellation

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
