# New ports collection makefile for:	R-cran-deldir
# Date created:		2011-08-16
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/math/R-cran-deldir/Makefile,v 1.9 2012/04/22 13:21:42 tota Exp $
#

PORTNAME=	deldir
DISTVERSION=	0.0-19
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Delaunay Triangulation and Dirichlet (Voronoi) Tessellation

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
