# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/graphics/R-cran-colorspace/Makefile 300896 2012-07-14 13:54:48Z beat $

PORTNAME=	colorspace
DISTVERSION=	1.2-0
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Color Space Manipulation

LICENSE=	BSD

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
