# New ports collection makefile for:	R-cran-colorspace
# Date created:		2011-09-10
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/graphics/R-cran-colorspace/Makefile,v 1.4 2011/11/27 07:02:09 bf Exp $
#

PORTNAME=	colorspace
DISTVERSION=	1.1-1
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Color Space Manipulation

LICENSE=	BSD

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
