# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/science/R-cran-Epi/Makefile 309935 2013-01-04 17:51:39Z bf $

PORTNAME=	Epi
PORTVERSION=	1.1.44
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Package for statistical analysis in epidemiology

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
