# New ports collection makefile for:	R-cran-Epi
# Date created:		2011-08-16
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/science/R-cran-Epi/Makefile,v 1.4 2011/11/27 07:02:13 bf Exp $
#

PORTNAME=	Epi
PORTVERSION=	1.1.24
PORTREVISION=	2
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	A package for statistical analysis in epidemiology

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
