# New ports collection makefile for:    tdiary
# Date created:                 21 May 2003
# Whom:                         Fumihiko Kimura <jfkimura@yahoo.co.jp>
#
# $FreeBSD: ports/japanese/tdiary/Makefile,v 1.10 2009/09/12 03:17:08 tota Exp $
#

CATEGORIES=	japanese www ruby

MAINTAINER=	tota@FreeBSD.org

TDIARY_LANG=	ja
MASTERDIR=	${.CURDIR}/../../www/tdiary

.include "${MASTERDIR}/Makefile"
