# Created by: Fumihiko Kimura <jfkimura@yahoo.co.jp>
# $FreeBSD: head/japanese/tdiary/Makefile 327737 2013-09-20 18:47:54Z bapt $

CATEGORIES=	japanese www ruby

MAINTAINER=	tota@FreeBSD.org

TDIARY_LANG=	ja
MASTERDIR=	${.CURDIR}/../../www/tdiary

.include "${MASTERDIR}/Makefile"
