#
# $FreeBSD: ports/devel/bugzilla3/Makefile.common,v 1.3 2011/07/18 21:56:01 ohauer Exp $
#

DIST_SUBDIR=	${PORTNAME}

CONFLICTS=	bugzilla-4.*

PORTSCOUT=	limitw:1,even

WWWDIR=	${PREFIX}/www/bugzilla

NO_BUILD=	yes

