# $FreeBSD$

PORTNAME=	gmail_xoauth
PORTVERSION=	0.3.2
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Get access to Gmail IMAP and STMP via OAuth

RUN_DEPENDS=	rubygem-oauth>=0.3.6:${PORTSDIR}/net/rubygem-oauth

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
