# New ports collection makefile for:	R-cran-reshape
# Date created:		2011-08-30
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/devel/R-cran-reshape/Makefile,v 1.4 2011/11/27 07:02:08 bf Exp $
#

PORTNAME=	reshape
PORTVERSION=	0.8.4
PORTREVISION=	2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	An R package for flexibly restructuring and aggregating data

LICENSE=	MIT

RUN_DEPENDS=	R-cran-plyr>0:${PORTSDIR}/devel/R-cran-plyr

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
