# New ports collection makefile for:	R-cran-KFAS
# Date created:		2012-01-04
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/math/R-cran-KFAS/Makefile,v 1.5 2012/07/07 07:15:51 tota Exp $
#

PORTNAME=	KFAS
PORTVERSION=	0.9.11
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Kalman filter and smoothers for exponential family state space models

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
