# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	libv8
PORTVERSION=	3.16.14.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby gem binary distribution of the V8 JavaScript engine

USE_RUBY=	yes
USE_RUBYGEMS=	yes
USE_PYTHON=	2
USE_GCC=	4.4+
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	${GEM_LIB_DIR}/vendor/v8/build/gyp

NO_STAGE=	yes
.include <bsd.port.mk>
