# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-bdsmatrix/Makefile 313562 2013-03-07 04:21:34Z bf $

PORTNAME=	bdsmatrix
DISTVERSION=	1.3-1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Routines for Block Diagonal Symmetric matrices

LICENSE=	LGPL20

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
