# New ports collection makefile for:	R-cran-bitops
# Date created:		2011-08-28
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/devel/R-cran-bitops/Makefile,v 1.4 2011/11/27 07:02:07 bf Exp $
#

PORTNAME=	bitops
DISTVERSION=	1.0-4.1
PORTREVISION=	2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Functions for Bitwise operations

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
