# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	jpstock
PORTVERSION=	0.6.1
CATEGORIES=	finance
MASTER_SITES=	RG

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Ruby library for extracting information about Japan stocks

LICENSE=	MIT

RUN_DEPENDS=	rubygem-nokogiri>=0:${PORTSDIR}/textproc/rubygem-nokogiri

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
