# New ports collection makefile for:	rubygem-libwebsocket
# Date created:		2012-08-19
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD$
#

PORTNAME=	libwebsocket
PORTVERSION=	0.1.5
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Universal Ruby library to handle WebSocket protocol

RUN_DEPENDS=	rubygem-addressable>=0:${PORTSDIR}/www/rubygem-addressable

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
