# New ports collection makefile for:	R-cran-XML
# Date created:		2011-08-06
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/textproc/R-cran-XML/Makefile,v 1.10 2012/01/22 03:37:18 tota Exp $
#

PORTNAME=	XML
DISTVERSION=	3.9-4
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Tools for parsing and generating XML

LICENSE=	BSD

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes
USE_GNOME=	libxml2

.include <bsd.port.mk>
