# New ports collection makefile for:	R-cran-xtable
# Date created:		2011-09-03
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/textproc/R-cran-xtable/Makefile,v 1.6 2012/01/18 23:04:07 bf Exp $
#

PORTNAME=	xtable
DISTVERSION=	1.7-0
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Export tables to LaTeX or HTML

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
