# New ports collection makefile for:	R-cran-xtable
# Date created:		2011-09-03
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/textproc/R-cran-xtable/Makefile,v 1.5 2011/11/27 07:02:14 bf Exp $
#

PORTNAME=	xtable
DISTVERSION=	1.6-0
PORTREVISION=	1
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Export tables to LaTeX or HTML

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
