# New ports collection makefile for:	rubygem-em-socksify
# Date created:		2012-06-10
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD$
#

PORTNAME=	em-socksify
PORTVERSION=	0.2.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	tota@FreeBSD.org
COMMENT=	EventMachine SOCKSify shim: adds SOCKS support to any protocol

RUN_DEPENDS=	rubygem-eventmachine>=1.0.0.b.4:${PORTSDIR}/devel/rubygem-eventmachine

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
