# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/graphics/R-cran-shape/Makefile 337846 2013-12-28 10:28:40Z dbn $

PORTNAME=	shape
PORTVERSION=	1.4.0
PORTREVISION=	5
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Functions for plotting graphical shapes, colors

LICENSE=	GPLv3

USES=	cran:auto-plist

.include <bsd.port.mk>
