# New ports collection makefile for:	R-cran-shape
# Date created:		2011-09-09
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: head/graphics/R-cran-shape/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	shape
PORTVERSION=	1.4.0
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Functions for plotting graphical shapes, colors

LICENSE=	GPLv3

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
