# New ports collection makefile for:	R-cran-RJSONIO
# Date created:		2011-09-03
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/converters/R-cran-RJSONIO/Makefile,v 1.8 2012/01/19 14:47:54 tota Exp $
#

PORTNAME=	RJSONIO
DISTVERSION=	0.98-1
CATEGORIES=	converters
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Serialize R objects to JSON, JavaScript Object Notation

LICENSE=	BSD

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
