# New ports collection makefile for:	rubygem-coderay
# Date created:		2011-08-01
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/textproc/rubygem-coderay/Makefile,v 1.8 2012/04/06 10:12:42 tota Exp $
#

PORTNAME=	coderay
PORTVERSION=	1.0.7
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Fast and easy syntax highlighting for selected languages

LICENSE=	LGPL21

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/coderay

.include <bsd.port.mk>
