# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/textproc/rubygem-coderay/Makefile 300897 2012-07-14 14:29:18Z beat $

PORTNAME=	coderay
PORTVERSION=	1.0.8
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Fast and easy syntax highlighting for selected languages

LICENSE=	LGPL21

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/coderay

.include <bsd.port.mk>
