# New ports collection makefile for:	R-cran-proto
# Date created:		2011-09-09
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/devel/R-cran-proto/Makefile,v 1.4 2011/11/27 07:02:08 bf Exp $
#

PORTNAME=	proto
DISTVERSION=	0.3-9.2
PORTREVISION=	2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Prototype object-based programming

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
