# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	minqa
PORTVERSION=	1.2.3
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Derivative-free optimization algorithms by quadratic approximation

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
