# $FreeBSD: $

PORTNAME=	atk
PORTVERSION=	1.1.5
CATEGORIES=	accessibility devel ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=        Ruby binding for ATK

RUN_DEPENDS=	rubygem-glib2>=1.1.5:${PORTSDIR}/devel/rubygem-glib2

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
