# New ports collection makefile for:	rubygem-http_parser.rb
# Date created:		2011-06-23
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/net/rubygem-http_parser.rb/Makefile,v 1.3 2011/10/02 04:51:47 tota Exp $
#

PORTNAME=	http_parser.rb
PORTVERSION=	0.5.3
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	tota@FreeBSD.org
COMMENT=	A simple callback-based HTTP request/response parser

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
