# New ports collection makefile for:	R-psych
# Date created:		2010-09-15
# Whom:			Dan Rue <drue@therub.org>
#
# $FreeBSD: ports/math/R-cran-psych/Makefile,v 1.12 2012/03/03 16:59:32 bf Exp $
#

PORTNAME=	psych
PORTVERSION=	1.2.1
CATEGORIES=	math science
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	drue@therub.org
COMMENT=	Psych package for the R project

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
