# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/graphics/R-cran-png/Makefile 337846 2013-12-28 10:28:40Z dbn $

PORTNAME=	png
DISTVERSION=	0.1-7
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Read and write PNG images

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

LIB_DEPENDS=	png15:${PORTSDIR}/graphics/png

USES=	cran:auto-plist

.include <bsd.port.mk>
