# New ports collection makefile for:	Ruby Locale gem (separated from Ruby GetText Package)
# Date created:		4 February 2002
# Whom:			Akinori MUSHA aka knu <knu@idaemons.org>
#
# $FreeBSD: head/devel/rubygem-locale/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	locale
PORTVERSION=	2.0.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	knu@FreeBSD.org
COMMENT=	A pure ruby library to support locales

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
