# New ports collection makefile for:	rubygem-rainbow
# Date created:		2012-01-11
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/devel/rubygem-rainbow/Makefile,v 1.1 2012/01/22 13:04:30 tota Exp $
#

PORTNAME=	rainbow
PORTVERSION=	1.1.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Extends ruby String class enabling coloring text on ANSI terminals

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
