# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	rugged
PORTVERSION=	0.19.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Ruby bindings to the libgit2 linkable C Git library

LICENSE=	MIT

LIB_DEPENDS=	libgit2.so:${PORTSDIR}/devel/libgit2

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
