# New ports collection makefile for:	R-cran-lmtest
# Date created:		2012-02-06
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD$
#

PORTNAME=	lmtest
DISTVERSION=	0.9-29
CATEGORIES=	finance
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Testing Linear Regression Models

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
