# New ports collection makefile for:	rubygem-rubyzip
# Date created:		2012-05-16
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD$
#

PORTNAME=	rubyzip
PORTVERSION=	0.9.9
CATEGORIES=	archivers rubygems
MASTER_SITES=	RG

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Rubyzip is a ruby module for reading and writing zip files

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
