# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-memisc/Makefile 337846 2013-12-28 10:28:40Z dbn $

PORTNAME=	memisc
DISTVERSION=	0.96-9
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Provides an infrastructure for the management of survey data

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
