# New ports collection makefile for:	R-cran-Rpad
# Date created:		2011-09-04
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/www/R-cran-Rpad/Makefile,v 1.4 2011/11/27 07:02:14 bf Exp $
#

PORTNAME=	Rpad
PORTVERSION=	1.3.0
PORTREVISION=	2
CATEGORIES=	www
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Workbook-style, web-based interface to R

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
